FROM node:18-alpine

WORKDIR /app

# Install dependencies first (cache)
COPY package*.json ./
RUN npm ci --only=production

# Copy code
COPY . .

# Expose (change if necessary)
EXPOSE 3000

# Start
CMD ["node", "index.js"]

